version: '3.8'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - WATCHPACK_POLLING=true
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    environment:
      - DEBUG=1