CREATE DATABASE cutter_db;

GRANT ALL PRIVILEGES ON DATABASE cutter_db TO example_user;

CREATE TABLE IF NOT EXISTS shortcuts (
   id SERIAL PRIMARY KEY,
   short_url VARCHAR(255) NOT NULL UNIQUE,
   full_url VARCHAR(2048) NOT NULL,
   public BOOLEAN NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   user_id INT
);
