apiVersion: apps/v1
kind: Deployment
metadata:
  name: cservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cservice
  template:
    metadata:
      labels:
        app: cservice
    spec:
      containers:
        - name: cservice
          image: ghcr.io/iokiris/shafo-cservice:1.0.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.5"
            requests:
              memory: "256Mi"
              cpu: "0.25"
          volumeMounts:
            - name: cservice-volume
              mountPath: /app/tmp
      volumes:
        - name: cservice-volume
          hostPath:
            path: ../../cservice
            type: Directory
