# Generated by Django 5.0.2 on 2024-02-28 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmtoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
